### Numpy 패키지와 배열(ndarray) 객체 

In [1]:
import numpy as np

In [2]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

array는 **`동질의 데이터`**를 다룰 수 있는 구조<br/>
빠른 접근 속도

In [3]:
np.array([1,2,3,4],dtype=np.float)

array([1., 2., 3., 4.])

**`데이터 타입`** 지정해서 구성 가능

In [5]:
np.array([range(i,i+3) for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**`초기화`** 가능한 여러 가지 함수

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

배열을 생성하는 **`np.arange`**

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

균등하게 interval을 구성할 수 있는 **`linspace`**

In [13]:
np.linspace(0,100,5,dtype=int)

array([  0,  25,  50,  75, 100])

 **`난수`** 와 관련된 함수

데이터 모의 구성시 많이 사용하는 `random함수`

In [14]:
np.random.random((3,3))

array([[0.86596194, 0.97402838, 0.8171547 ],
       [0.25609258, 0.14415804, 0.33208368],
       [0.08952383, 0.28661124, 0.32453523]])

범위를 제공하는 `randint`

In [15]:
np.random.randint(0,10,(3,3))

array([[9, 8, 6],
       [1, 1, 3],
       [2, 2, 6]])

정규분포를 나타내는 `normal` <br/>

평균과 표준편차 데이터 입력

In [16]:
np.random.normal(0,1,(3,3))

array([[-0.87651011,  0.32408356,  0.00196429],
       [-1.13801697, -0.30357086,  0.24498621],
       [ 0.0846116 , -0.64859596,  0.39572584]])

**`seed 함수`**를 통해 재현성 문제 해결 가능

In [20]:
np.random.seed(0)

arr1=np.random.randint(10,size=6)
arr2=np.random.randint(10,size=(2,3))

print('arr1 : \n%s'%arr1)
print('ndim : %d shape : %s, size : %d, dtype : %s\n'%
     (arr1.ndim, arr1.shape,arr1.size, arr1.dtype))
print('arr2 : \n%s'%arr2)
print('ndim : %d shape : %s, size : %d, dtype : %s\n'%
     (arr2.ndim, arr2.shape,arr2.size, arr2.dtype))

arr1 : 
[5 0 3 3 7 9]
ndim : 1 shape : (6,), size : 6, dtype : int32

arr2 : 
[[3 5 2]
 [4 7 6]]
ndim : 2 shape : (2, 3), size : 6, dtype : int32



ndim : 차원의 정보 <br/>
shape : 행/열, 원소의 구조 <br/>
size : 원소의 갯수 <br/>
dtype : data type 

### Numpy 배열 객체의 인덱싱 

단일 원소에 접근하는 기법, **`인덱싱`**

In [21]:
arr1

array([5, 0, 3, 3, 7, 9])

In [22]:
arr1[0], arr1[5]

(5, 9)

In [24]:
arr1[-6],arr1[-1]

(5, 9)

In [25]:
arr2

array([[3, 5, 2],
       [4, 7, 6]])

In [28]:
arr2[0,0],arr2[0,2]

(3, 2)

In [29]:
arr2[-1,-3], arr2[-1,-1]

(4, 6)

In [30]:
arr2[0,0]=9
arr2

array([[9, 5, 2],
       [4, 7, 6]])

Numpy 배열 객체의 슬라이싱

In [32]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr1[0:5:1]

array([0, 1, 2, 3, 4])

In [34]:
arr1[:5:1]

array([0, 1, 2, 3, 4])

In [35]:
arr1[:5:],arr1[:5]

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [37]:
arr1[2:9:2], arr1[2::2]

(array([2, 4, 6, 8]), array([2, 4, 6, 8]))

In [38]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
arr1[-1:-11:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
arr1[5::-1]

array([5, 4, 3, 2, 1, 0])

형태 변환

In [49]:
arr2=np.arange(12).reshape(-1,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
arr2[:3,:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
arr2[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
arr2[:2,:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [53]:
arr2[:2,2::-1]

array([[2, 1, 0],
       [6, 5, 4]])

In [54]:
arr2[1:,-1]

array([ 7, 11])

In [55]:
arr2[-1,:],arr2[-1]

(array([ 8,  9, 10, 11]), array([ 8,  9, 10, 11]))

### Numpy 배열 객체의 연결

In [56]:
list1=[1,2,3]
list2=[4,5,6]

concatenate 함수 사용시 **list안에** 담겨 전달!!

In [57]:
np.concatenate([list1,list2])

array([1, 2, 3, 4, 5, 6])

**`axis`**라는 파라미터를 이용해 **`방향지정`**

In [59]:
arr1=np.concatenate([list1,list2],axis=0)
arr1

array([1, 2, 3, 4, 5, 6])

In [61]:
arr2=arr1.reshape(-1,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.concatenate([arr2,arr2],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([arr2,arr2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
np.vstack([arr2,arr2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
np.hstack([arr2,arr2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### Numpy 배열 객체의 내장 함수 사용<br>
빠른 연산이 가능한 **`vectorize function`**

In [66]:
np.random.seed(0)

arr2=np.random.randint(1,10,(3,4))
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [67]:
np.sum(arr2), arr2.sum()

(65, 65)

In [70]:
np.sum(arr2,axis=0),arr2.sum(axis=0)

(array([19, 13, 17, 16]), array([19, 13, 17, 16]))

In [71]:
np.sum(arr2,axis=1),arr2.sum(axis=1)

(array([15, 21, 29]), array([15, 21, 29]))

In [72]:
np.min(arr2,axis=0), np.max(arr2,axis=0)

(array([5, 1, 4, 3]), array([8, 8, 7, 9]))

In [73]:
arr2.min(axis=0),arr2.max(axis=0)

(array([5, 1, 4, 3]), array([8, 8, 7, 9]))

In [74]:
np.min(arr2,axis=1),np.max(arr2,axis=1)

(array([1, 3, 5]), array([6, 8, 9]))

In [75]:
arr2.min(axis=1),arr2.max(axis=1)

(array([1, 3, 5]), array([6, 8, 9]))

### Numpy 배열 객체와 브로드캐스팅<br>
행열 구조를 동일하게 맞춰주는 **`브로드캐스팅`**

In [77]:
np.random.seed(0)

X=np.random.random((10,3))
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [78]:
Xmean=X.mean(axis=0)
Xmean

array([0.52101579, 0.62614181, 0.59620338])

In [79]:
Xcentered=X-Xmean
Xcentered

array([[ 0.02779771,  0.08904756,  0.00655999],
       [ 0.02386739, -0.20248701,  0.04969073],
       [-0.08342858,  0.26563119,  0.36745938],
       [-0.13757427,  0.16558323, -0.06730846],
       [ 0.04702877,  0.29945483, -0.52516732],
       [-0.43388649, -0.60592341,  0.23641646],
       [ 0.25714096,  0.24387034,  0.38241496],
       [ 0.27814277, -0.16466245,  0.18432579],
       [-0.40274137,  0.01377921, -0.45285009],
       [ 0.42365312, -0.10429349, -0.18154144]])

### Numpy 배열 객체의 부울 배열과 마스킹 연산 

In [80]:
np.random.seed(0)

X=np.random.randint(1,10,size=(3,4))
X

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [85]:
(X>5)&(X<8)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False]])

In [86]:
np.sum((X>5)&(X<8))

3

In [87]:
np.sum((X>5)|(X<8))

12

In [88]:
np.sum((X>5)&(X<8),axis=0)

array([1, 0, 2, 0])

In [89]:
np.sum((X>5)&(X<8),axis=1)

array([1, 1, 1])

In [90]:
X[(X>5)&(X<8)]

array([6, 6, 7])

### Numpy 배열 객체와 팬시 인덱스<br>
인덱스를 담고 있는 배열, **`팬시인덱스`**

In [91]:
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
row = np.array([0,1,2])
col = np.array([1,2,3])

In [94]:
X[row]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
X[:,col]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [96]:
X[row,col]

array([ 1,  6, 11])

In [97]:
X[row.reshape(-1,1),col]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

### Numpy 배열 객체와 복합 인덱싱 

In [99]:
X=np.zeros(12).reshape((3,4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
X[1,0]=1
X

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
X[1,[1,3]]=1
X

array([[0., 0., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [102]:
X[[0,2],[1,3]]=2
X

array([[0., 2., 0., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 2.]])

In [103]:
X[0:3,[0,2]]=3
X

array([[3., 2., 3., 0.],
       [3., 1., 3., 1.],
       [3., 0., 3., 2.]])

### Numpy 배열 객체의 정렬 

In [109]:
np.random.seed(0)

x=np.array(np.random.randint(10,size=5))
x

array([5, 0, 3, 3, 7])

In [110]:
np.sort(x)

array([0, 3, 3, 5, 7])

In [111]:
x

array([5, 0, 3, 3, 7])

np.sort의 경우 원본데이터 변화 X

In [112]:
x.sort()

In [113]:
x

array([0, 3, 3, 5, 7])

변수.sort()의 경우 원본데이터 변화O

sort된 인덱스를 정렬하는 **`argsort함수`**

In [114]:
np.random.seed(0)

x=np.array(np.random.randint(10,size=5))
x

array([5, 0, 3, 3, 7])

In [117]:
idx=np.argsort(x)
idx

array([1, 2, 3, 0, 4], dtype=int64)

In [118]:
x[idx]

array([0, 3, 3, 5, 7])